name: NPM Package Publish

on:
  push:
    branches:
      - master
      - next

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check version changes
        uses: EndBug/version-check@v2
        id: check

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Setup Node
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Get yarn cache
        if: steps.check.outputs.changed == 'true'
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.5
        if: steps.check.outputs.changed == 'true'
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        if: steps.check.outputs.changed == 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Run Unit Tests + Coverage
        if: steps.check.outputs.changed == 'true'
        env:
          CODE_CLIMATE: ${{ secrets.CODE_CLIMATE }}
        run: yarn test:cov

      - name: Build
        if: steps.check.outputs.changed == 'true' && success()
        run: yarn build

      - name: Archive Build Artifact
        uses: actions/upload-artifact@master
        if: steps.check.outputs.changed == 'true' && success()
        with:
          name: firebase-ci-build
          path: lib

      - name: Publish To NPM
        if: steps.check.outputs.changed == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish $(if [ ${{github.ref}} == 'refs/heads/next' ]; then echo '--tag next';fi;)

      - name: Upload Coverage + Climate
        if: steps.check.outputs.changed == 'true' && success()
        env:
          CODE_COV: ${{ secrets.CODE_COV }}
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODE_CLIMATE }}
        # Upload to Code Coverage. Curl used in place of codecov/codecov-action
        # due to long build time. See https://github.com/codecov/codecov-action/issues/21
        run: |
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
          npm install -g codeclimate-test-reporter
          codeclimate-test-reporter < coverage/lcov.info
