name: NPM Package Publish

on:
  push:
    branches:
      - master
      - next

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check package version
        uses: technote-space/package-version-check-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        env:
          CI: true
        run: |
          yarn install --frozen-lockfile

      - name: Run Unit Tests + Coverage
        env:
          CI: true
          CODE_CLIMATE: ${{ secrets.CODE_CLIMATE }}
        run: yarn test:cov && yarn codecov

      - name: Build
        if: success()
        run: yarn build

      - name: Archive Build Artifact
        uses: actions/upload-artifact@master
        if: success()
        with:
          name: firebase-ci-build
          path: lib

      - name: Publish To NPM
        run: npm publish $(if [ ${{github.ref}} == 'refs/heads/next' ]; then echo '--tag next';fi;)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload Coverage + Climate
        if: success()
        env:
          CI: true
          CODE_COV: ${{ secrets.CODE_COV }}
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODE_CLIMATE }}
        run: |
          # Upload to Code Cover. Curl used in place of codecov/codecov-action
          # due to long build time. See https://github.com/codecov/codecov-action/issues/21
          curl -s https://codecov.io/bash | bash -s -- -t $CODE_COV
          # Install codeclimate tool and upload
          npm install -g codeclimate-test-reporter
          codeclimate-test-reporter < coverage/lcov.info
