name: Verify

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      # Setup dependency caching
      - uses: actions/cache@v3.0.7
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Install Dependencies
        run: |
          yarn install --frozen-lockfile

      - name: Run Unit Tests + Coverage
        run: yarn test:cov

      - name: Upload Coverage + Climate
        env:
          CODE_COV: ${{ secrets.CODE_COV }}
          CODECLIMATE_REPO_TOKEN: ${{ secrets.CODE_CLIMATE }}
        run: |
          # Upload to Code Cover. Curl used in place of codecov/codecov-action
          # due to long build time. See https://github.com/codecov/codecov-action/issues/21
          bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
          # Install codeclimate tool and upload
          npm install -g codeclimate-test-reporter
          codeclimate-test-reporter < coverage/lcov.info